---
root: true
env:
  es6: true
  browser: true
  node: true
parser: "@typescript-eslint/parser"
parserOptions:
  project: "./tsconfig.eslint.json"
settings:
  react:
    version: detect
  import/resolver:
    typescript: []
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:react-hooks/recommended
  - plugin:jsx-a11y/recommended
  - plugin:tailwindcss/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - prettier
rules:
  prefer-const: error
  prefer-arrow-callback: error
  no-restricted-imports:
    [error, { paths: [{ name: react, importNames: [default] }] }]
  "@typescript-eslint/consistent-type-imports": [warn, { prefer: type-imports }]
  "@typescript-eslint/no-unused-vars":
    [error, { varsIgnorePattern: "^_", argsIgnorePattern: "^_" }]
  react/prop-types: off
  react/self-closing-comp: error
  react/jsx-curly-brace-presence: error
  react/jsx-pascal-case: error
  import/order:
    [error, { newlines-between: always, warnOnUnassignedImports: true }]
overrides:
  - files:
      ["**/__tests__/**/*.+(ts|tsx|js)", "**/?(*.)+(spec|test).+(ts|tsx|js)"]
    extends: ["plugin:testing-library/react"]
